[window]
opacity = 1.0
blur = false
dynamic_padding = true

[font]
size = 12
builtin_box_drawing = true
offset.y = -1

[font.normal]
family = "Inconsolata"
style = "Regular"

[font.bold]
family = "Inconsolata"
style = "Bold"

[font.italic]
family = "Inconsolata"
style = "Regular"

[font.bold_italic]
family = "Inconsolata"
style = "Bold"

[selection]
save_to_clipboard = true

# Default colors
[colors.primary]
background = '#000000'
foreground = '#ffffff'

# Cursor colors
[colors.cursor]
text   = '#ffffff'
cursor = '#007FFF'

# Normal colors
[colors.normal]
black   = '#000000'
white   = '#ffffff'
red     = '#e85468'
green   = '#54ca83'
blue    = '#007FFF'
yellow  = '#edda53'
magenta = '#ff80ff'
cyan    = '#70e1e8'

# Bright colors
[colors.bright]
black   = '#464646'
white   = '#ffffff'
red     = '#EE8391'
green   = '#83D8A5'
blue    = '#46A2FF'
yellow  = '#F2E482'
magenta = '#FFA3FF'
cyan    = '#97E9EE'

[keyboard]
bindings = [
  {key = ']', mods = 'Control', action = 'IncreaseFontSize'},
  {key = '[', mods = 'Control', action = 'DecreaseFontSize'},
  {key = '=', mods = 'Control', action = 'ResetFontSize'}
]
